server:
  port: 8081
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
  instance:
    hostame: localhost
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        id: user-service
        uri: lb://user-service
        predicates:
          - Path=/user/**