server:
  port: 8085
spring:
  cloud:
    config:
      server:
        git:
          default-label: master
          uri: https://github.com/matiassanroman/microservicios.git
          search-paths: config-data
          bootstrap: true
        enabled: true
  application:
    name: config-service
