server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: master
          uri:
          search-paths: config-data
  application:
    name: config-service
