server:
  port: 8181
spring:
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/matiassanroman/microservicios
          search-paths: config-data
  application:
    name: config-service